import {type ProjectOptions, type TemplateDefinition} from '#shared/types.js';
import {getTemplateDir} from '#shared/file.js';

export const getWebWidgetTemplate = (_opts: ProjectOptions): TemplateDefinition => ({
	name: 'web-widget',
	description: 'A publishable native TypeScript web widget with a Vite demo, package build, API docs, and screenshots.',
	components: [
		{name: 'Native TypeScript Widget', description: 'Dependency-free DOM component published as an ESM package.'},
		{name: 'tsdown', description: 'Builds ESM library artifacts and declaration files for npm publishing.'},
		{name: 'Vite', description: 'Runs and builds the documentation/demo site.'},
		{name: 'TypeDoc', description: 'Generates API documentation for the public package surface.'},
		{name: 'Stylelint', description: 'Lints the widget and demo stylesheets.'},
		{name: 'Playwright', description: 'Runs e2e checks and captures demo screenshots.'},
	],
	dependencies: {},
	devDependencies: {
		vite: 'vite',
		vitest: 'vitest',
		'@vitest/browser': '@vitest/browser',
		'@vitest/browser-playwright': '@vitest/browser-playwright',
		playwright: 'playwright',
		'@playwright/test': '@playwright/test',
		tsdown: 'tsdown',
		typedoc: 'typedoc',
		stylelint: 'stylelint',
		'stylelint-config-standard': 'stylelint-config-standard',
		react: 'react',
		'react-dom': 'react-dom',
		'@types/react': '@types/react',
		'@types/react-dom': '@types/react-dom',
	},
	scripts: {
		dev: 'vite',
		build: 'vite build',
		'build:lib': 'tsdown',
		'build:demo': 'vite build',
		'docs:api': 'typedoc',
		preview: 'vite preview',
		start: 'vite preview --port 4173 --strictPort',
		test: 'vitest run',
		'test:ui': 'vitest',
		'integration-test': 'playwright test',
		'lint:css': "stylelint 'src/{demo,styles}/**/*.css'",
		'lint:css:fix': "stylelint --fix 'src/{demo,styles}/**/*.css'",
		screenshot: 'node scripts/screenshot.mjs',
	},
	files: [],
	templateDir: getTemplateDir(import.meta.dirname, 'web-widget'),
});
