name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

# [PM_SETUP]

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "{{packageManager}}"

      - name: Verify {{packageManager}}
        run: {{packageManager}} --version

      - name: Install dependencies
        run: {{installCommand}}

# [PLAYWRIGHT_SETUP]

      - name: Lint
        run: {{packageManager}} run lint

      - name: Build
        run: {{packageManager}} run build

      - name: Unit test
        run: {{packageManager}} run test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2

      - name: Integration test
        run: {{packageManager}} run integration-test
